name = "m10c"
license = "MIT"
licenselink = "https://github.com/vaga/hugo-theme-m10c/blob/master/LICENSE.md"
description = "A minimalistic (m10c) theme for bloggers"
homepage = "https://github.com/vaga/hugo-theme-m10c"
tags = ["blog", "minimalistic", "minimal", "responsive", "dark"]
features = [
  "minimalistic blog",
  "social icons",
  "editable colors"
]
min_version = 0.43

[author]
  name = "vaga"
  homepage = "https://vaga.io"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts/"
    weight = -110
  [[menu.main]]
    identifier = "kubernetes"
    name = "kubernetes"
    title = "kubernetes"
    url = "kubernetes"
    weight = 100
